backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Yhdistys"
        name: "index"
        fields:
          - {label: Kicker, name: kicker, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: "body", widget: "markdown"}
      - file: "src/pages/boffaus.md"
        label: "Boffaus"
        name: "boffaus"
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/larppaus.md"
        label: "Larppaus"
        name: "larppaus"
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
      - file: "src/pages/tapahtumatoiminta.md"
        label: "Tapahtumatoiminta"
        name: "tapahtumatoiminta"
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}